"""Deterministic Flip 7 game mechanics and state."""

from flip7.core.actions import (
    ActionKind,
    Flip7ActionError,
    HitAction,
    InvalidActionError,
    InvalidTargetError,
    LegalAction,
    StayAction,
    TargetAction,
    TurnAction,
    legal_targets,
    legal_turn_actions,
    validate_target_action,
    validate_turn_action,
)
from flip7.core.cards import (
    ActionCard,
    ActionCardName,
    Card,
    ModifierCard,
    ModifierCardName,
    NumberCard,
    card_counts,
    create_standard_deck,
)
from flip7.core.deck import Deck, EmptyDeckError
from flip7.core.engine import (
    EventKind,
    Flip7Engine,
    GameEvent,
    TransitionResult,
)
from flip7.core.scoring import (
    FLIP7_BONUS,
    ScoreBreakdown,
    calculate_round_scores,
    score_cards,
)
from flip7.core.state import (
    Flip7StateError,
    GamePhase,
    GameState,
    InvalidPhaseError,
    InvalidPlayerCountError,
    InvalidPlayerError,
    PendingAction,
    PendingFlipThree,
    PlayerState,
    PlayerStatus,
    RoundPhase,
    create_initial_state,
)

__all__ = [
    "ActionKind",
    "ActionCard",
    "ActionCardName",
    "Card",
    "Deck",
    "EmptyDeckError",
    "EventKind",
    "Flip7ActionError",
    "Flip7Engine",
    "GameEvent",
    "Flip7StateError",
    "GamePhase",
    "GameState",
    "HitAction",
    "InvalidActionError",
    "InvalidPhaseError",
    "InvalidPlayerCountError",
    "InvalidPlayerError",
    "InvalidTargetError",
    "LegalAction",
    "ModifierCard",
    "ModifierCardName",
    "NumberCard",
    "PendingAction",
    "PendingFlipThree",
    "PlayerState",
    "PlayerStatus",
    "RoundPhase",
    "ScoreBreakdown",
    "StayAction",
    "TargetAction",
    "TransitionResult",
    "TurnAction",
    "card_counts",
    "calculate_round_scores",
    "create_standard_deck",
    "create_initial_state",
    "legal_targets",
    "legal_turn_actions",
    "score_cards",
    "validate_target_action",
    "validate_turn_action",
    "FLIP7_BONUS",
]
